### ISSUE TITLE
mhchem doesn't seem to work with rehype-katex

### ISSUE THREAD

**Issue by djoudimansouri-ti** [remarkjs/remark-math#97] opened 2024-04-10 12:01 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Node version : v21.5.0
NPM version : 10.2.4
PNPM version : 8.13.1

I'm using the `rehype-katex` plugin in `react-markdown` in a Nextjs14 app, and while KaTeX seem to work and displays maths equations and symbols with little to no issues, i can't say the same for chimical reactions, even the KaTeX package imports the mhchem module and declares the macros properly, i can't seem to get it to work in my app, in which i call the plugin like this : 

```
        <ReactMarkdown
            className="prose break-words dark:prose-invert prose-p:leading-relaxed prose-pre:p-0"
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeKatex]}
            components={{
              p({ children }) {
                return <p className="mb-2 last:mb-0 ">{children}</p>
              },
            }}
          >
             {`$\ce{Hg^2+ ->[I-] HgI2 ->[I-] [Hg^{II}I4]^2-}$`} 
          </ReactMarkdown>
```

### Expected behavior

The chemical reaction equation should be properly formated and show this : 

![image](https://github.com/remarkjs/remark-math/assets/160012917/c0fc70b7-bd1c-4914-80d2-f819bdb1216a)

### Actual behavior

Instead, nothing is happening, it's style displayed like this : 

`\ce{Hg^2+ ->[I-] HgI2 ->[I-] [Hg^{II}I4]^2-}`

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment] 2024-04-10 12:08
See: https://github.com/remarkjs/remark-math/issues/81#issuecomment-1434803831.
See: https://github.com/remarkjs/remark-math/pull/34#issuecomment-527345050

Duplicate of #34

**Closed by wooorm** 2024-04-10 12:08 UTC
Labels: 🤞 phase/open

**Comment by wooorm** [comment] 2024-04-10 12:36
Duplicate of #34
